# Dependencies
highlighter: rouge
markdown: kramdown

# Setup
title: Franco Chalissery
tagline: "A Personal Page"
description: "Personal blog about new technologies"
url:
baseurl: /

# Custom vars
socials_links:
  - url: https://github.com/ca-franco
    class: fab fa-github
  - url: https://linkedin.com/in/francochalissery
    class: fab fa-linkedin
  - url: https://x.com/fchaliss
    class: fab fa-twitter

github:
  repo: https://github.com/ca-franco

plugins: [kramdown, rouge]

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  works:
    output: true
